name: Deploy Prerelease

# when a tag is created with the format vx.y.z or x.y.z
on:
  push:
    tags:
      - "*.*.*-*"
      - "v*.*.*-*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Run packager for live
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p $CF_PROJECT_ID -w $WOWI_PROJECT_ID
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          CF_PROJECT_ID: 26754
          WOWI_PROJECT_ID: 23157
      - name: Run packager for classic
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g $WOW_VERSION -p $CF_PROJECT_ID -w $WOWI_PROJECT_ID
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WOW_VERSION: ${{ secrets.WOW_CLASSIC_VERSION }}
          CF_PROJECT_ID: 26754
          WOWI_PROJECT_ID: 23157
