name: Prerlease packager

# when a v1.0.0-alpha|beta tag is created
on:
  push:
    tags: ^v?([0-9]+\.[0-9]+\.[0-9]+)-([A-Za-z]+)([0-9]*)$

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      env:
         CF_API_KEY: ${{ secrets.CF_API_KEY }}
         GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
         WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
         CF_PROJECT_ID: 26754
         WOWI_PROJECT_ID: 23157
    - name: Run packager for live
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -p CF_PROJECT_ID -w WOWI_PROJECT_ID
    - name: Run packager for classic
      run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -g 1.13.3 -p CF_PROJECT_ID -w WOWI_PROJECT_ID
